version: 2.1
orbs:
  node: circleci/node@5
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cimg/node:18.3.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Yarn install
          command: "yarn install"
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: yarn build
          command: yarn buildprod
      - persist_to_workspace:
          root: ~/project
          paths: .
      - run:
          name: Deploy app to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN
workflows:
  build-and-deploy:
    jobs:
      - build
